spring:
  datasource:
    url: jdbc:mysql://aliyun:3306/pms?useUnicode=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: tellMeWhoAmI?
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: aliyun
    password: tellMeWhoAmI?
    port: 6379
    database: 0
config:
  file-upload:
    host-name: 127.0.0.1
