mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: @activatedProperties@
#    active: dev
server:
  port: 8080
  servlet:
    context-path: /api