
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: tellMeWhoAmI?
  redis:
    host: localhost
    password: tellMeWhoAmI?
    port: 6379
    database: 0
config:
  file-upload:
    host-name: https://hylexus.online/zxb-pms
server:
  port: 8090
